name: medication_control
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  firebase_storage: ^12.4.2
  shared_preferences: ^2.5.2
  introduction_screen: ^3.1.16
  fluttertoast: ^8.2.12
  awesome_snackbar_content: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assests/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assests/fonts/Montserrat-Regular.ttf
        - asset: assests/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assests/fonts/Montserrat-Italic.ttf
          style: italic

