// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/* /// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// ); */
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQayc_JNoiYRCeix5ATdIdO4gQwh5T9f0',
    appId: '1:916904538680:web:fe24b916aefdd0020b6ccd',
    messagingSenderId: '916904538680',
    projectId: 'medication-control-6d6a9',
    authDomain: 'medication-control-6d6a9.firebaseapp.com',
    storageBucket: 'medication-control-6d6a9.firebasestorage.app',
    measurementId: 'G-RPSBXPZWD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtqobOEOlbv1l4jY13yDe9QM6_YaLnX40',
    appId: '1:916904538680:android:b20b690ceb44edbe0b6ccd',
    messagingSenderId: '916904538680',
    projectId: 'medication-control-6d6a9',
    storageBucket: 'medication-control-6d6a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC412HG8gErnCxElRqmh5QhXGMuj2l4zs8',
    appId: '1:916904538680:ios:2d4851633e295c8a0b6ccd',
    messagingSenderId: '916904538680',
    projectId: 'medication-control-6d6a9',
    storageBucket: 'medication-control-6d6a9.firebasestorage.app',
    iosBundleId: 'com.example.medicationControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC412HG8gErnCxElRqmh5QhXGMuj2l4zs8',
    appId: '1:916904538680:ios:2d4851633e295c8a0b6ccd',
    messagingSenderId: '916904538680',
    projectId: 'medication-control-6d6a9',
    storageBucket: 'medication-control-6d6a9.firebasestorage.app',
    iosBundleId: 'com.example.medicationControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQayc_JNoiYRCeix5ATdIdO4gQwh5T9f0',
    appId: '1:916904538680:web:065f2490e965acfd0b6ccd',
    messagingSenderId: '916904538680',
    projectId: 'medication-control-6d6a9',
    authDomain: 'medication-control-6d6a9.firebaseapp.com',
    storageBucket: 'medication-control-6d6a9.firebasestorage.app',
    measurementId: 'G-Z72E6761RK',
  );
}
